### ISSUE TITLE
WARNING: Impossible de joindre https://.../pbxep/payment/ipn/ pour le paiement / Erreur : code HTTP: 500

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [PayboxByVerifone/Magento2#22]
Bonjour,

Depuis la mise à jour de Magento vers 2.2.6, j'ai eu plusieurs paiements revenus avec un warning (6 sur 20 jours). La commande n'apparaît pas comme payée pour Magento et elle reste donc en Pending.

`WARNING: Impossible de joindre https://.../pbxep/payment/ipn/ pour le paiement "..."
Erreur : code HTTP: 500`

Je n'ai aucun warning de surcharge d'activité ou de serveur down aux moments de ces commandes.

Serveur dédié Linux (Centos 6.9) avec Plesk Onyx (Version 17.5.3 Mise à jour n° 57)
PHP 7.0.32
Magento 2.2.6
Paybox 1.0.9
Multi boutiques avec sous domaines

Une idée de ce qui pourrait se passer svp ?

**Comment by bm-services** [comment]
Bonjour,

Est-ce qu'il serait possible d'avoir le détail de l'erreur 500?

Merci

**Comment by ShapesGraphicStudio** [comment]
Bonjour,
Je ne la trouve pas dans mes logs malheureusement.
Le souci s'est reproduit, toujours dans les mêmes conditions.

**Comment by ShapesGraphicStudio** [comment]
Bonjour @jcpaybox et @bm-services,
Est-ce que vous avez pu étudier ce problème ?

**Comment by ShapesGraphicStudio** [comment]
Bonjour,

Toujours pas de nouvel à ce sujet.. ?
Depuis la mise à jour vers 2.3.0, il semble que le souci se soit propagé à une autre boutique du site.

**Comment by ShapesGraphicStudio** [comment]
Suite à la mise à jour vers 2.3.0 le problème semble s'être étendu à toutes les boutiques et aux comptes registered. 

J'ai dû bloquer les commandes aux utilisateurs enregistrés, ce qui avait réglé le souci sous 2.2.6, mais ça ne semble pas aider aujourd'hui, et nous avons vu une baisse du nombre de commandes suite à ce blocage.

J'ai pu trouver une trace d'hier soir dans mes logs, je vais continuer à documenter ce thread quand j'aurai plus d'éléments à disposition.

```
[2018-12-10 21:45:36] main.CRITICAL: Exception message: This email address is already subscribed.
Trace: #0 /var/www/vhosts/mondomaine.com/httpdocs/generated/code/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php(24): Magento\Newsletter\Controller\Subscriber\NewAction->execute()
#1 /var/www/vhosts/mondomaine.com/httpdocs/vendor/magento/framework/App/Action/Action.php(108): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->execute()
#2 /var/www/vhosts/mondomaine.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/vhosts/mondomaine.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callParent('dispatch', Array)
#4 /var/www/vhosts/mondomaine.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#5 /var/www/vhosts/mondomaine.com/httpdocs/generated/code/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php(39): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callPlugins('dispatch', Array, Array)
#6 /var/www/vhosts/mondomaine.com/httpdocs/vendor/magento/framework/App/FrontController.php(159): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /var/www/vhosts/mondomaine.com/httpdocs/vendor/magento/framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor))
#8 /var/www/vhosts/mondomaine.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /var/www/vhosts/mondomaine.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#10 /var/www/vhosts/mondomaine.com/httpdocs/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /var/www/vhosts/mondomaine.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /var/www/vhosts/mondomaine.com/httpdocs/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /var/www/vhosts/mondomaine.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /var/www/vhosts/mondomaine.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /var/www/vhosts/mondomaine.com/httpdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#16 /var/www/vhosts/mondomaine.com/httpdocs/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /var/www/vhosts/mondomaine.com/httpdocs/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#18 /var/www/vhosts/mondomaine.com/httpdocs/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#19 /var/www/vhosts/mondomaine.com/httpdocs/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#20 {main} [] []
```

**Comment by ShapesGraphicStudio** [comment]
Le dernier retour de PayBox reçu est de type : 

```
WARNING: Impossible de joindre https://www.mondomaine.com/default/pbxep/payment/ipn/ pour le paiement "..."
Erreur : code HTTP: 302
```

**Comment by ShapesGraphicStudio** [comment]
Je peux voir également certaines lignes avec : 

`"POST /france/pbxep/payment/ipn/ HTTP/1.0" 302 1189 "-" "Paybox System IPN"`

dans mes logs

**Comment by ShapesGraphicStudio** [comment]
À l'époque, j'avais installé le module par FTP, je viens de le supprimer pour le ré-installer via composer.
Je vais tester ça.

**Comment by ShapesGraphicStudio** [comment]
Le souci est maintenant systématique, sur toutes les vues boutiques, en guest comme en registered, donc j'ai réactivé les commandes en guest.

**Comment by ShapesGraphicStudio** [comment]
Après réactivation des commandes en guest, je peux voir que le code d'erreur du warning est également 302 et non plus 500.

```
WARNING: Impossible de joindre https://europe.mondomaine.com/france/pbxep/payment/ipn/ pour le paiement "..."
Erreur : code HTTP: 302
```

**Comment by dankocrama980** [comment]
nous avons le même problème y at-il des nouvelles sur ce problème?

**Comment by ShapesGraphicStudio** [comment]
Aucune nouvelle malheureusement malgré de nombreuses relances ici, par mail, téléphone...
J'ai monté 3 versions de Magento pour faire des tests (fresh install avec sample data) : 
_ 2.2.3 qui fontionnait bien à l'époque
_ 2.2.6 qui a commencé à présenter quelques bugs
_ 2.3.0 où plus aucun retour de paiement ne passe (le paiement se fait bien, mais le retour ne se fait pas, donc les commandes restent en mode pending et les emails de confirmation de paiements ne sont pas envoyés)

Il apparaît bien que la dernière version qui est fonctionnelle / stable avec ce repository est Magento 2.2.3. J'en ai informé l'équipe de développement avec toutes les infos.

**Comment by jcpaybox** [comment]
Bonjour,

Nous avons remonté les échanges auprès du développeur, nous vous tiendrons informés dès qu'une solution aura été trouvée.

Pardonnez-nous le peu de réactivité sur ce canal, n'hésitez pas à priviliégier les mails ou le téléphone. pou rappel une adresse spécifique à magento existe: magento-paybox@verifone.com.

Cordialement,

@jcpaybox

**Comment by Tibo16** [comment]
Bonjour,

Je rencontre EXACTEMENT le même souci.
Une solution a-t-elle été trouvée depuis fin février ?

Merci !
Thibaut

**Comment by ShapesGraphicStudio** [comment]
@Tibo16 , toujours rien non...

**Comment by Tibo16** [comment]
Je pense avoir réglé le problème avec moins de 10 lignes de code. Je fais quelques tests supplémentaires dans la soirée ou demain et si c'est OK, je partage ici !
Qui sait, sans doute Paybox voudra m'embaucher après :)

**Comment by Tibo16** [comment]
Alors, après avoir pas mal creusé, le problème vient du retour serveur de Paybox qui envoie les variables de retour en $_POST.
Or, depuis quelques versions Magento ne traite ces données, comme toutes les données postées depuis un formulaire, qu'à la condition qu'il y ait avec un champ de signature. Forcément, cette signature est absente du retour de Paybox.
Dès lors, 2 solutions 
- intercepter le retour et y ajouter une signature
- autoriser pour ce module spécifiquement le traitement des données sans signature.

C'est sur cette seconde solution que je suis parti.
Du coup, j'ai modifié le controller IPN : paybox>epayment>Controller>Payment>Ipn.php
Après la déclaration du namespace, ajouter : 

```
use Magento\Framework\App\RequestInterface;
use Magento\Framework\App\Request\InvalidRequestException;
use Magento\Framework\App\CsrfAwareActionInterface;
```
Modifier la déclaration de la classe : 
class Ipn extends \Paybox\Epayment\Controller\Payment **implements CsrfAwareActionInterface**

Puis ajouter les deux fonctions suivantes qui permettent de se passer de la signature : 
```
   public function createCsrfValidationException(RequestInterface $request): ?InvalidRequestException
    {
        return null;
    }

    public function validateForCsrf(RequestInterface $request): ?bool
    {
        return true;
    }
```

Après ça, logiquement, plus d'erreur (évidemment, flush cache etc...) et un retour complet qui permet de retrouver les details de la transaction dans la commande, de déclencher la facture automatique te le mail associé etc !

A ceux qui testeront, par curiosité, confirmez moi que c'est OK pour vous aussi !

**Comment by ShapesGraphicStudio** [comment]
@Tibo16 
Je viens d'essayer d'intégrer vos modifications mais je coince sur les cartes de test de PayBox qui sont refusées.. :-(

**Comment by Tibo16** [comment]
Pour le coup, je ne vois pas le lien entre le mode 3D Secure et la réponse IPN. Ca reste une variable qui est renvoyée en POST, sans doute effectivement avec une variable supplémentaire ou une valeur de retour différente...
Peut être faire un test avec une vraie carte en mode production, parce que franchement, je ne vois pas le lien.
Content en tout cas que ca arrange votre situation.

**Comment by ShapesGraphicStudio** [comment]
Non, aucun lien effectivement, juste un bug supplémentaire côté PayBox qui n'aide pas les tests.
J'ai essayé hier avec cette même carte que vous, mais elle était refusée directement sur la page de paiement avec le code R sans retour au site.

Je vais refaire des tests dés que possible.

**Comment by ShapesGraphicStudio** [comment]
@Tibo16 , sans nouvelles de l'équipe VerifOne, j'ai passé votre commit en production, et ça s'avère bien concluant, merci encore !!

**Comment by Tibo16** [comment]
Ravi d'avoir pu aider.
Je trouve néanmoins surprenant que ce souci ne concerne pas plus de personnes...
J'ai en outre découvert que le module ne semble pas vérifier le serveur à l'origine des requêtes alors que la doc de l'API e-transaction (basée sur paybox donc), indique qu'il est fortement recommandé de ne traiter que les appels API en provenance des IP "officielles".
Bonne soirée :)

**Comment by JoachimCanu** [comment]
> Alors, après avoir pas mal creusé, le problème vient du retour serveur de Paybox qui envoie les variables de retour en $_POST.
> Or, depuis quelques versions Magento ne traite ces données, comme toutes les données postées depuis un formulaire, qu'à la condition qu'il y ait avec un champ de signature. Forcément, cette signature est absente du retour de Paybox.
> Dès lors, 2 solutions
> 
> * intercepter le retour et y ajouter une signature
> * autoriser pour ce module spécifiquement le traitement des données sans signature.
> 
> C'est sur cette seconde solution que je suis parti.
> Du coup, j'ai modifié le controller IPN : paybox>epayment>Controller>Payment>Ipn.php
> Après la déclaration du namespace, ajouter :
> 
> ```
> use Magento\Framework\App\RequestInterface;
> use Magento\Framework\App\Request\InvalidRequestException;
> use Magento\Framework\App\CsrfAwareActionInterface;
> ```
> 
> Modifier la déclaration de la classe :
> class Ipn extends \Paybox\Epayment\Controller\Payment **implements CsrfAwareActionInterface**
> 
> Puis ajouter les deux fonctions suivantes qui permettent de se passer de la signature :
> 
> ```
>    public function createCsrfValidationException(RequestInterface $request): ?InvalidRequestException
>     {
>         return null;
>     }
> 
>     public function validateForCsrf(RequestInterface $request): ?bool
>     {
>         return true;
>     }
> ```
> 
> Après ça, logiquement, plus d'erreur (évidemment, flush cache etc...) et un retour complet qui permet de retrouver les details de la transaction dans la commande, de déclencher la facture automatique te le mail associé etc !
> 
> A ceux qui testeront, par curiosité, confirmez moi que c'est OK pour vous aussi !

Bonjour,

J'ai toujours le code 302...
Pourriez-vous m'aider ?

Merci

**Comment by kevinvuillemin** [comment]
Bonjour,

Un grand merci @Tibo16  nous avions rencontré le même problème.

Néanmoins aucun retour de @jcpaybox   ?

**Comment by ShapesGraphicStudio** [comment]
Bonjour,

Suite à une mise à jour vers 2.3.3 j'ai dû ré-appliquer le patch de @Tibo16 , il serait bien que l'équipe de @jcpaybox règle ça avec un commit.
